version: "3"
services:
  node:
    container_name: node
    image: thaichain/gochain
    ports:
      # Proxy
      - "7545:8000"
      # Explorer
      - "8088:8080"
      - "30333:30333"
    volumes:
      - ./gochain:/gochain/node
    command: gochain --networkid 7 --datadir /gochain/node --cache 4096 --port 30333 --rpc
    restart: always
  proxy:
    container_name: proxy
    image: gcr.io/gochain-core/rpc-proxy:${RPC_PROXY_IMAGE:-latest}
    depends_on:
      - node
    network_mode: "service:node"
    command: -port 8000 -url http://localhost:8545 -allow "rpc_modules,eth_getCode,clique_getSnapshotAtHash,clique_getSignersAtHash,clique_getVotersAtHash,clique_getSnapshot,clique_getSigners,clique_getVoters,eth_chainId,eth_call,eth_blockNumber,eth_getBalance,eth_sendRawTransaction,eth_gasPrice,eth_estimateGas,net_version,eth_getTransaction,eth_getTransactionReceipt,eth_getTransactionCount,eth_getFilterChanges,net_listening,eth_getBlockByHash,eth_uninstallFilter,eth_getBlockByNumber,eth_newBlockFilter,eth_newPendingTransactionFilter,eth_totalSupply,eth_getLogs,eth_getStorageAt" -rpm 10000
    restart: always
